import numpy as np
temp=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(temp)
print(temp.dtype)
print(temp.shape)
print(temp.size)
zero=np.zeros((2,3))
print(zero)
rng=np.arange(9)
print(rng)
rng1=rng.reshape(3,3)
print(rng1)
lspace=np.linspace(1,10,5)
print(lspace)
emp=np.empty((4,2))
print(emp)